# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

version: 0.2.dev0-{build}

branches:
  only:
  - master

environment:
  matrix:
    - PYTHON: 3.5

install:
  - "set PATH=C:\\Miniconda3-x64;C:\\Miniconda3-x64\\Scripts;%PATH%"

  # Install the build and runtime dependencies of the project.
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda install -q conda-build anaconda-client"
  - "conda info -a"

  # Check that we have the expected version of Python
  - "python --version"

build: off

before_test:
  - "conda build -q buildscripts/condarecipes/cephes --python %PYTHON%"
  #- "conda build -q glpk --python %PYTHON%"

# Actual test here
test_script:
  - "echo XXX Test here XXX"

